/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacePackage;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Bruno César Klein
 */
public class ClientScreen extends javax.swing.JFrame {

	public static String[][] cards = new String[9][4];
	JLabel[] labels = {this.LabelmgOne, this.LabelmgTwo, this.LabelmgThree, this.LabelmgFour, this.LabelmgFive, this.LabelmgSix, this.LabelmgSeven, this.LabelmgEight, this.LabelmgNine};
	public static String discardcard = "";
	public ImageIcon img;

	/**
	 * Creates new form ClientScreen
	 */
	public ClientScreen() {
		initComponents();
		getContentPane().setBackground(Color.GREEN);
		//"pictureOfTheCards/10_of_clubs.png")
	}

	public void addCards(String[][] handCards) {
		cards = handCards;
		customerHand(cards) ;
	}

	public void customerHand(String[][] cards) {
		for (int i = 0; i < cards.length; i++) {
			img = new ImageIcon(getClass().getResource(cards[i][1]));
			img.setImage(img.getImage().getScaledInstance(labels[i].getWidth(), labels[i].getHeight(), 100));
			labels[i].setIcon(img);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelmgOne = new javax.swing.JLabel();
        ButtonDropLetter = new javax.swing.JButton();
        LabelmgTwo = new javax.swing.JLabel();
        LabelmgFour = new javax.swing.JLabel();
        LabelmgSeven = new javax.swing.JLabel();
        LabelmgNine = new javax.swing.JLabel();
        LabelmgFive = new javax.swing.JLabel();
        LabelmgThree = new javax.swing.JLabel();
        LabelmgSix = new javax.swing.JLabel();
        LabelmgEight = new javax.swing.JLabel();
        LabelCardTable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ButtonPickUpLetter = new javax.swing.JButton();
        ButtonBuyLetter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ButtonHit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        LabelmgOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LabelmgOne.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LabelmgOneMouseDragged(evt);
            }
        });
        LabelmgOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelmgOneMouseClicked(evt);
            }
        });

        ButtonDropLetter.setBackground(new java.awt.Color(153, 204, 255));
        ButtonDropLetter.setText("Largar na mesa");
        ButtonDropLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDropLetterActionPerformed(evt);
            }
        });

        LabelmgTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LabelmgTwo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LabelmgTwoMouseDragged(evt);
            }
        });
        LabelmgTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelmgTwoMouseClicked(evt);
            }
        });

        LabelmgFour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LabelmgFour.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LabelmgFourMouseDragged(evt);
            }
        });
        LabelmgFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelmgFourMouseClicked(evt);
            }
        });

        LabelmgSeven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LabelmgSeven.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LabelmgSevenMouseDragged(evt);
            }
        });
        LabelmgSeven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelmgSevenMouseClicked(evt);
            }
        });

        LabelmgNine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LabelmgNine.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LabelmgNineMouseDragged(evt);
            }
        });
        LabelmgNine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelmgNineMouseClicked(evt);
            }
        });

        LabelmgFive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LabelmgFive.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LabelmgFiveMouseDragged(evt);
            }
        });
        LabelmgFive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelmgFiveMouseClicked(evt);
            }
        });

        LabelmgThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LabelmgThree.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LabelmgThreeMouseDragged(evt);
            }
        });
        LabelmgThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelmgThreeMouseClicked(evt);
            }
        });

        LabelmgSix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LabelmgSix.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LabelmgSixMouseDragged(evt);
            }
        });
        LabelmgSix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelmgSixMouseClicked(evt);
            }
        });

        LabelmgEight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LabelmgEight.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LabelmgEightMouseDragged(evt);
            }
        });
        LabelmgEight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelmgEightMouseClicked(evt);
            }
        });

        LabelCardTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Carta na mesa");

        ButtonPickUpLetter.setText("Pegar mesa");
        ButtonPickUpLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPickUpLetterActionPerformed(evt);
            }
        });

        ButtonBuyLetter.setText("Comprar carta");

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ButtonHit.setText("Bater");
        ButtonHit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabelmgOne, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(LabelmgTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(LabelmgThree, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(LabelmgFour, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(LabelmgFive, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(LabelmgSix, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(LabelmgSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LabelmgEight, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(LabelmgNine, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(LabelCardTable, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonPickUpLetter, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(ButtonBuyLetter)
                .addGap(35, 35, 35)
                .addComponent(ButtonDropLetter)
                .addGap(33, 33, 33)
                .addComponent(ButtonHit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelmgThree, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelmgOne, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelmgTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelmgFour, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelmgFive, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelmgSix, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelmgSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelmgEight, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelmgNine, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCardTable, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonPickUpLetter)
                            .addComponent(ButtonBuyLetter)
                            .addComponent(ButtonDropLetter)
                            .addComponent(ButtonHit))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(120, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelmgOneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgOneMouseDragged
		// TODO add your handling code here:
		LabelmgOne.setLocation(LabelmgOne.getLocation().x + evt.getX() - LabelmgOne.getWidth() / 2, LabelmgOne.getLocation().y + evt.getY() - LabelmgOne.getHeight() / 2);
		discardcard = LabelmgOne.toString();
    }//GEN-LAST:event_LabelmgOneMouseDragged

    private void LabelmgOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgOneMouseClicked
		// TODO add your handling code here:
		discardcard = LabelmgOne.toString();
    }//GEN-LAST:event_LabelmgOneMouseClicked

    private void LabelmgTwoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgTwoMouseDragged
		// TODO add your handling code here:
		LabelmgTwo.setLocation(LabelmgTwo.getLocation().x + evt.getX() - LabelmgTwo.getWidth() / 2, LabelmgTwo.getLocation().y + evt.getY() - LabelmgTwo.getHeight() / 2);
		discardcard = LabelmgTwo.toString();
    }//GEN-LAST:event_LabelmgTwoMouseDragged

    private void LabelmgTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgTwoMouseClicked
		// TODO add your handling code here:
		discardcard = LabelmgTwo.toString();
    }//GEN-LAST:event_LabelmgTwoMouseClicked

    private void LabelmgThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgThreeMouseClicked
		// TODO add your handling code here:
		discardcard = LabelmgThree.toString();
    }//GEN-LAST:event_LabelmgThreeMouseClicked

    private void LabelmgThreeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgThreeMouseDragged
		// TODO add your handling code here:
		LabelmgThree.setLocation(LabelmgThree.getLocation().x + evt.getX() - LabelmgThree.getWidth() / 2, LabelmgThree.getLocation().y + evt.getY() - LabelmgThree.getHeight() / 2);
		discardcard = LabelmgThree.toString();
    }//GEN-LAST:event_LabelmgThreeMouseDragged

    private void LabelmgFourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgFourMouseClicked
		// TODO add your handling code here:
		discardcard = LabelmgFour.toString();
    }//GEN-LAST:event_LabelmgFourMouseClicked

    private void LabelmgFourMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgFourMouseDragged
		// TODO add your handling code here:
		LabelmgFour.setLocation(LabelmgFour.getLocation().x + evt.getX() - LabelmgFour.getWidth() / 2, LabelmgFour.getLocation().y + evt.getY() - LabelmgFour.getHeight() / 2);
		discardcard = LabelmgFour.toString();
    }//GEN-LAST:event_LabelmgFourMouseDragged

    private void LabelmgFiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgFiveMouseClicked
		// TODO add your handling code here:
		discardcard = LabelmgFive.toString();
    }//GEN-LAST:event_LabelmgFiveMouseClicked

    private void LabelmgFiveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgFiveMouseDragged
		// TODO add your handling code here:
		LabelmgFive.setLocation(LabelmgFive.getLocation().x + evt.getX() - LabelmgFive.getWidth() / 2, LabelmgFive.getLocation().y + evt.getY() - LabelmgFive.getHeight() / 2);
		discardcard = LabelmgFive.toString();
    }//GEN-LAST:event_LabelmgFiveMouseDragged

    private void LabelmgSixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgSixMouseClicked
		// TODO add your handling code here:
		discardcard = LabelmgSix.toString();
    }//GEN-LAST:event_LabelmgSixMouseClicked

    private void LabelmgSixMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgSixMouseDragged
		// TODO add your handling code here:
		LabelmgSix.setLocation(LabelmgSix.getLocation().x + evt.getX() - LabelmgSix.getWidth() / 2, LabelmgSix.getLocation().y + evt.getY() - LabelmgSix.getHeight() / 2);
		discardcard = LabelmgSix.toString();
    }//GEN-LAST:event_LabelmgSixMouseDragged

    private void LabelmgSevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgSevenMouseClicked
		// TODO add your handling code here:
		discardcard = LabelmgSeven.toString();
    }//GEN-LAST:event_LabelmgSevenMouseClicked

    private void LabelmgSevenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgSevenMouseDragged
		// TODO add your handling code here:
		LabelmgSeven.setLocation(LabelmgSeven.getLocation().x + evt.getX() - LabelmgSeven.getWidth() / 2, LabelmgSeven.getLocation().y + evt.getY() - LabelmgSeven.getHeight() / 2);
		discardcard = LabelmgSeven.toString();
    }//GEN-LAST:event_LabelmgSevenMouseDragged

    private void LabelmgEightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgEightMouseClicked
		// TODO add your handling code here:
		discardcard = LabelmgEight.toString();
    }//GEN-LAST:event_LabelmgEightMouseClicked

    private void LabelmgEightMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgEightMouseDragged
		// TODO add your handling code here:
		LabelmgEight.setLocation(LabelmgEight.getLocation().x + evt.getX() - LabelmgEight.getWidth() / 2, LabelmgEight.getLocation().y + evt.getY() - LabelmgEight.getHeight() / 2);
		discardcard = LabelmgEight.toString();
    }//GEN-LAST:event_LabelmgEightMouseDragged

    private void LabelmgNineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgNineMouseClicked
		// TODO add your handling code here:
		discardcard = LabelmgNine.toString();
    }//GEN-LAST:event_LabelmgNineMouseClicked

    private void LabelmgNineMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelmgNineMouseDragged
		// TODO add your handling code here:
		LabelmgNine.setLocation(LabelmgNine.getLocation().x + evt.getX() - LabelmgNine.getWidth() / 2, LabelmgNine.getLocation().y + evt.getY() - LabelmgNine.getHeight() / 2);
		discardcard = LabelmgNine.toString();
    }//GEN-LAST:event_LabelmgNineMouseDragged

    private void ButtonDropLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDropLetterActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ButtonDropLetterActionPerformed

    private void ButtonPickUpLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPickUpLetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPickUpLetterActionPerformed

    private void ButtonHitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonHitActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ClientScreen().setVisible(true);

			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuyLetter;
    private javax.swing.JButton ButtonDropLetter;
    private javax.swing.JButton ButtonHit;
    private javax.swing.JButton ButtonPickUpLetter;
    private javax.swing.JLabel LabelCardTable;
    private javax.swing.JLabel LabelmgEight;
    private javax.swing.JLabel LabelmgFive;
    private javax.swing.JLabel LabelmgFour;
    private javax.swing.JLabel LabelmgNine;
    private javax.swing.JLabel LabelmgOne;
    private javax.swing.JLabel LabelmgSeven;
    private javax.swing.JLabel LabelmgSix;
    private javax.swing.JLabel LabelmgThree;
    private javax.swing.JLabel LabelmgTwo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
